include:
  - board: xiao_ble
    shield: IIIQBall-Foot_r
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: IIIQBall-Foot_l
  - board: xiao_ble
    shield: IIIQBall-Foot_f
  - board: xiao_ble
    shield: settings_reset