# 基本設定
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y

# 親機（ドングル）が左右のバッテリー残量を取得するための設定
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# トラックボール等のデータを受信・処理するために必要
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# ZMK Studio（親機で動作させる必要があります）
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 通信安定化（ドングルは複数と繋がるため電波を強めに設定）
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_STATUS_ADVERTISEMENT=y

CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="IIIQBall-Foot"


CONFIG_ZMK_STATUS_ADV_ACTIVITY_BASED=y

CONFIG_ZMK_STATUS_ADV_ACTIVE_INTERVAL_MS=100

CONFIG_ZMK_STATUS_ADV_IDLE_INTERVAL_MS=30000

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="FOOT"

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y