# ===== 基本設定 (Central) =====
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_USB_LOGGING=n

# 左右(L/R)の子機の情報を取得するための設定
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=1800
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# ポインティング設定 (F側にマウスキー等がある場合)
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y


CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 通信設定 (安定性のために2M PHYをオフ)
CONFIG_BT_CTLR_PHY_2M=n

# ===== Prospector (Status Advertisement) 設定 =====
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="IIIQBall-Foot"

# 親機の位置設定
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="LEFT"

# 電力と更新頻度
CONFIG_ZMK_STATUS_ADV_ACTIVITY_BASED=y
CONFIG_ZMK_STATUS_ADV_ACTIVE_INTERVAL_MS=100
CONFIG_ZMK_STATUS_ADV_IDLE_INTERVAL_MS=30000

# WPM計算
CONFIG_ZMK_STATUS_ADV_WPM_WINDOW_SECONDS=30

# ===== 3分割用のスロット割り当て =====
# 左手側(l)をスロット0、右手側(r)をスロット1に想定
CONFIG_ZMK_STATUS_ADV_HALF_PERIPHERAL=0
CONFIG_ZMK_STATUS_ADV_AUX1_PERIPHERAL=1

CONFIG_PINCTRL=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2